### ISSUE TITLE
wrong attendance marked

### ISSUE THREAD

**Issue by avichalsethi98** [NANOPHOTONIC-RESEARCH-SOCIETY-AT-PEC/COMPILED-ATTENDANCE-TILL-Sep-1-2020#1]
![image](https://user-images.githubusercontent.com/70662938/92027533-507a2380-ed80-11ea-828a-4897e589bbd0.png)

I was present on 7th and 10th august and the attendance is wrongly marked in the excel sheet.
@designerguy13-photonics

**Comment by designerguy13-photonics** [comment]
Avichal that is right but it was a claim form which was posted after the lecture while your meet attendance record says a different story

**Comment by designerguy13-photonics** [comment]
updated!
