### ISSUE TITLE
Attendance wrongly marked

### ISSUE THREAD

**Issue by i-pvg** [NANOPHOTONIC-RESEARCH-SOCIETY-AT-PEC/COMPILED-ATTENDANCE-TILL-Sep-1-2020#2]
![attendance](https://user-images.githubusercontent.com/39810908/92063045-cc439280-edb7-11ea-870b-8535ec3625ea.jpg)

Sir, I was present on 7th and 25th August, yet I am marked absent in the excel sheet. 
Kindly look into this.

Parth Vineel Garg

**Comment by designerguy13-photonics** [comment]
Noted!

**Comment by i-pvg** [comment]
PFA the snippet of Inspection of my chrome history for filling the form for 7th August for the exact time-stamp for your records.
Also from the previous Screenshot I shared, there was no filling of form on 25th August, hence no proof form filling.
![IMG_20200903_091933__01__01](https://user-images.githubusercontent.com/39810908/92069410-e33db100-edc6-11ea-80f4-dc478dd8304f.jpg)

**Comment by designerguy13-photonics** [comment]
Done.... Thanks for the claim! 

Will be updated !!
