### ISSUE TITLE
Attendance wrongly marked-17105002

### ISSUE THREAD

**Issue by tejashwip** [NANOPHOTONIC-RESEARCH-SOCIETY-AT-PEC/COMPILED-ATTENDANCE-TILL-Sep-1-2020#3]
![WhatsApp Image 2020-09-03 at 11 01 06 (1)](https://user-images.githubusercontent.com/69338291/92074946-01121280-edd5-11ea-9e4f-25ff064a5460.jpeg)
![WhatsApp Image 2020-09-03 at 11 01 06](https://user-images.githubusercontent.com/69338291/92074950-03746c80-edd5-11ea-9356-2b56fda69e43.jpeg)

Sir, I had attended both the lecture and tutorial on the 7th and 25th of August and had filled the form for the same. I kindly request you to look into this.

Thanks.

**Comment by tejashwip** [comment]
![z3](https://user-images.githubusercontent.com/69338291/92076041-6961f380-edd7-11ea-8c87-f60ac2739ebd.JPG)
![z2](https://user-images.githubusercontent.com/69338291/92076045-6bc44d80-edd7-11ea-9011-87ba2b551a17.JPG)
![z1](https://user-images.githubusercontent.com/69338291/92076047-6c5ce400-edd7-11ea-8d32-b02a7f76f271.JPG)

Sir, please find my google history showing meet attendance. The timing are 15 minutes late because I am currently in Nepal. Also, on 7th I had submitted the tutorial sheet as well which is graded.

**Comment by designerguy13-photonics** [comment]
GREAT ! 
@tejashwip 

THANKS FOR THE CLAIM WITH DETAILED PROOF!

WILL BE UPDATED SOON!

GLAD TO SEE YOU ON GIT!

**Comment by tejashwip** [comment]
THANK YOU FOR THE PROMPT RESPONSE SIR!
