### ISSUE TITLE
Attendence marked wrongly for 6 august- 17105050

### ISSUE THREAD

**Issue by sahil-kansal** [NANOPHOTONIC-RESEARCH-SOCIETY-AT-PEC/COMPILED-ATTENDANCE-TILL-Sep-1-2020#4]
![6 august](https://user-images.githubusercontent.com/66944699/92104806-7eeb1380-edff-11ea-842c-ac8316b9391d.png)

**Comment by designerguy13-photonics** [comment]
marked! will be updated soon

**Comment by designerguy13-photonics** [comment]
Actually it has already been updated

check the updated sheet on the history of commits

f0ee6d3
