### ISSUE TITLE
17105016- Attendance not rectified for Aug-28.

### ISSUE THREAD

**Issue by kashyappatel544** [NANOPHOTONIC-RESEARCH-SOCIETY-AT-PEC/COMPILED-ATTENDANCE-TILL-Sep-1-2020#5]

**Comment by designerguy13-photonics** [comment]
please attach a proof here against the claim

**Comment by kashyappatel544** [comment]
![20200903_195502](https://user-images.githubusercontent.com/70704249/92127957-7efb0b80-ee1f-11ea-97ac-7f73d0d61720.jpg)

**Comment by kashyappatel544** [comment]
The assignment submission is the proof. I hope this will work.

**Comment by designerguy13-photonics** [comment]
Great will be updated
