### ISSUE TITLE
Marked absent for 25th aug

### ISSUE THREAD

**Issue by tanmaykaushik1** [NANOPHOTONIC-RESEARCH-SOCIETY-AT-PEC/COMPILED-ATTENDANCE-TILL-Sep-1-2020#6]
I was present on the 25th of august. Have been graded for the same in the classroom as well. Please check 
Thank you

**Comment by designerguy13-photonics** [comment]
attach proof here!

**Comment by tanmaykaushik1** [comment]
![image](https://user-images.githubusercontent.com/70685626/92225331-ae158980-eec0-11ea-9d8b-124cfa6393fd.png)

**Comment by designerguy13-photonics** [comment]
# Its Done
