### ISSUE TITLE
Marked Absent for 25th August (17105031)

### ISSUE THREAD

**Issue by Anirudh-Naqib** [NANOPHOTONIC-RESEARCH-SOCIETY-AT-PEC/COMPILED-ATTENDANCE-TILL-Sep-1-2020#7]
![Annotation 2020-09-04 002956](https://user-images.githubusercontent.com/70720544/92157111-964def00-ee47-11ea-94cc-50b9d945287b.png)

**Comment by designerguy13-photonics** [comment]
updated

**Comment by Anirudh-Naqib** [comment]
Thank u Sir
