### ISSUE TITLE
Wrongly marked absent for 20,24 and 25th Aug

### ISSUE THREAD

**Issue by ashish1601git** [NANOPHOTONIC-RESEARCH-SOCIETY-AT-PEC/COMPILED-ATTENDANCE-TILL-Sep-1-2020#8]
![Screenshot_20200904_005817](https://user-images.githubusercontent.com/70719865/92158792-107f7300-ee4a-11ea-8717-77e6f6b88c01.jpg)
![Screenshot_20200904_005749](https://user-images.githubusercontent.com/70719865/92158799-12e1cd00-ee4a-11ea-9d6a-71ddb9d22883.jpg)
![Screenshot_20200904_005741](https://user-images.githubusercontent.com/70719865/92158803-1412fa00-ee4a-11ea-87c7-14871e8a2609.jpg)
Please sir see to the above lectures. I was present in all 3 of them.

**Comment by designerguy13-photonics** [comment]
updated

**Comment by ashish1601git** [comment]
Sir I doesn't show up in the link to me. I can't figure out how to see the updated one. I an getting the exact same sheet as before.

**Comment by designerguy13-photonics** [comment]
@ashish1601git  find the link here 

https://github.com/NANOPHOTONIC-RESEARCH-SOCIETY-AT-PEC/Dr_NEENA_GUPTA_CLASSROOM/blob/master/ATTENDANCE-UPDATES

**Comment by designerguy13-photonics** [comment]
but it is always better to use PC version as an when possible
